FROM node:16-alpine
WORKDIR /app/client
COPY  ./client-app/package.json ./
COPY  ./client-app/tsconfig.json ./
COPY  ./client-app/yarn.lock ./
RUN npm install --save prop-types
RUN npm install -g create-react-app
RUN yarn install && \
  yarn build
COPY . ./
EXPOSE 3000
CMD ["yarn", "start"]
