version: '3'
services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: react_container
    tty: true
    volumes:
    - ./client:/app/client
    command: sh -c "cd /app/client/client-app && yarn start"
    ports:
      - 3000:3000