version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    container_name: mysql_container
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: react_golang_mux
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  client:
    build:
      # ?Git位置を指定
      context: .
      # dockerfileの位置を指定
      dockerfile: ./client/Dockerfile
    container_name: react_container
    tty: true
    volumes:
    - ./client:/app/client
    command: sh -c "cd /app/client/client-app && yarn start"
    ports:
      - 3000:3000
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: go_container
    volumes:
      - ./api:/app/api
    ports:
      - 8000:8000
    depends_on:
      - mysql
    tty: true
  nginx:
    image: nginx
    container_name:  nginx_container
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
