FROM golang:alpine
WORKDIR /app/api
RUN export GOPATH= && export GO111MODULE=on 
COPY ./ /app/api
RUN apk upgrade --update && \
  apk --no-cache add git gcc musl-dev
COPY go.mod ./
RUN go mod download
COPY go.sum .
COPY . .

RUN go get -d -v
RUN go install -v

EXPOSE 8000

CMD ["./main"]